/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseTemplate: typeof import('./src/components/echarts/BaseTemplate.vue')['default']
    Donation: typeof import('./src/components/echarts/Donation.vue')['default']
    DonationCount: typeof import('./src/components/echarts/DonationCount.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    MenuBar: typeof import('./src/components/menu/MenuBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SexRatio: typeof import('./src/components/echarts/SexRatio.vue')['default']
    SexRatioComponent: typeof import('./src/components/echarts/SexRatioComponent.vue')['default']
    TestPage: typeof import('./src/components/echarts/TestPage.vue')['default']
    UserCount: typeof import('./src/components/echarts/UserCount.vue')['default']
    UserNum: typeof import('./src/components/echarts/UserNum.vue')['default']
    VisitRecord: typeof import('./src/components/echarts/VisitRecord.vue')['default']
  }
}
